export const urlISDatabaseAPI = "https://api.github.com/repos/Illegal-Services/IS.Bookmarks/commits?path=IS.bookmarks.json&sha=extra&per_page=1";
export const urlRawISDatabase = "https://raw.githubusercontent.com/Illegal-Services/IS.Bookmarks/extra/IS.bookmarks.json";
export const illegalIds = ["tags________"];
export const defaultBookmarkSaveLocation = "toolbar_____";
export const failureImportingISdatabase = "Failed";
export const successImportingISdatabase = "Completed";
export const enabledButtonClass = "btn btn-primary w-50 enabled";
export const successButtonClass = "btn btn-success w-50";
export const secondaryDisabledButtonClass = "btn btn-secondary w-50 disabled";
export const dangerDisabledButtonClass = "btn btn-danger w-50 disabled";
